[package]
name = "wot-td-embedded"
version = "0.1.0"
edition = "2021"
authors = ["Jan Romann <jan.romann@uni-bremen.de>"]
keywords = ["web-of-things", "webofthings", "wot", "iot", "embedded", "no_std"]

[dependencies]
